GET http://localhost:3000/api
Content-Type: application/json

###

GET http://localhost:3000/api/0003

###

POST http://localhost:3000/api/add
Content-Type: application/json

{
    "id": "",
    "class": "Psi-Mutant",
    "weapon": "Baseballbat",
    "description": "Jag är en psi-mutant!"
}

###

PUT http://localhost:3000/api/update/0004
Content-Type: application/json

{
    "class": "test",
    "weapon": "test",
    "description": "test"
}

###

DELETE http://localhost:3000/api/delete/0005